/* ============================================================
   QR Code Generator
   ============================================================ */
var QRCodeGenerator = (function(){
  function QRCode(e,t){this.typeNumber=e;this.errorCorrectLevel=t;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}
  QRCode.prototype={addData:function(e){this.dataList.push(new QR8bitByte(e));this.dataCache=null},isDark:function(e,t){return this.modules[e][t]},getModuleCount:function(){return this.moduleCount},make:function(){this.makeImpl(false,this.getBestMaskPattern())},makeImpl:function(e,t){this.moduleCount=4*this.typeNumber+17;this.modules=new Array(this.moduleCount);for(var n=0;n<this.moduleCount;n++){this.modules[n]=new Array(this.moduleCount);for(var r=0;r<this.moduleCount;r++)this.modules[n][r]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(e,t);if(this.typeNumber>=7)this.setupTypeNumber(e);if(this.dataCache==null)this.dataCache=QRCode.createData(this.typeNumber,this.errorCorrectLevel,this.dataList);this.mapData(this.dataCache,t)},setupPositionProbePattern:function(e,t){for(var n=-1;n<=7;n++){if(e+n<=-1||this.moduleCount<=e+n)continue;for(var r=-1;r<=7;r++){if(t+r<=-1||this.moduleCount<=t+r)continue;this.modules[e+n][t+r]=(0<=n&&n<=6&&(r==0||r==6))||(0<=r&&r<=6&&(n==0||n==6))||(2<=n&&n<=4&&2<=r&&r<=4)}}},getBestMaskPattern:function(){var e=0,t=0;for(var n=0;n<8;n++){this.makeImpl(true,n);var r=QRUtil.getLostPoint(this);if(n==0||e>r){e=r;t=n}}return t},setupTimingPattern:function(){for(var e=6;e<this.moduleCount-8;e++)if(this.modules[e][6]==null)this.modules[e][6]=(e%2==0);for(var t=6;t<this.moduleCount-8;t++)if(this.modules[6][t]==null)this.modules[6][t]=(t%2==0)},setupPositionAdjustPattern:function(){var e=QRUtil.getPatternPosition(this.typeNumber);for(var t=0;t<e.length;t++){for(var n=0;n<e.length;n++){var r=e[t],i=e[n];if(this.modules[r][i]!=null)continue;for(var o=-2;o<=2;o++){for(var a=-2;a<=2;a++){this.modules[r+o][i+a]=(o==-2||o==2||a==-2||a==2||(o==0&&a==0))}}}}},setupTypeNumber:function(e){var t=QRUtil.getBCHTypeNumber(this.typeNumber);for(var n=0;n<18;n++){var r=!e&&((t>>n)&1)==1;this.modules[Math.floor(n/3)][n%3+this.moduleCount-8-3]=r}for(var n=0;n<18;n++){var r=!e&&((t>>n)&1)==1;this.modules[n%3+this.moduleCount-8-3][Math.floor(n/3)]=r}},setupTypeInfo:function(e,t){var n=(this.errorCorrectLevel<<3)|t;var r=QRUtil.getBCHTypeInfo(n);for(var i=0;i<15;i++){var o=!e&&((r>>i)&1)==1;if(i<6)this.modules[i][8]=o;else if(i<8)this.modules[i+1][8]=o;else this.modules[this.moduleCount-15+i][8]=o}for(var i=0;i<15;i++){var o=!e&&((r>>i)&1)==1;if(i<8)this.modules[8][this.moduleCount-i-1]=o;else if(i<9)this.modules[8][15-i-1+1]=o;else this.modules[8][15-i-1]=o}this.modules[this.moduleCount-8][8]=!e},mapData:function(e,t){var n=-1,r=this.moduleCount-1,i=7,o=0;for(var a=this.moduleCount-1;a>0;a-=2){if(a==6)a--;while(true){for(var s=0;s<2;s++){if(this.modules[r][a-s]==null){var u=false;if(o<e.length)u=(((e[o]>>>i)&1)==1);var f=QRUtil.getMask(t,r,a-s);if(f)u=!u;this.modules[r][a-s]=u;i--;if(i==-1){o++;i=7}}}r+=n;if(r<0||this.moduleCount<=r){r-=n;n=-n;break}}}}};
  QRCode.PAD0=0xEC;QRCode.PAD1=0x11;
  QRCode.createData=function(e,t,n){var r=RSBlock.getRSBlocks(e,t);var i=new QRBitBuffer();for(var o=0;o<n.length;o++){var a=n[o];i.put(a.mode,4);i.put(a.getLength(),QRUtil.getLengthInBits(a.mode,e));a.write(i)}var s=0;for(var o=0;o<r.length;o++)s+=r[o].dataCount;if(!r.length)throw new Error("QR overflow");if(i.getLengthInBits()>s*8)throw new Error("QR overflow");if(i.getLengthInBits()+4<=s*8)i.put(0,4);while(i.getLengthInBits()%8!=0)i.putBit(false);while(true){if(i.getLengthInBits()>=s*8)break;i.put(QRCode.PAD0,8);if(i.getLengthInBits()>=s*8)break;i.put(QRCode.PAD1,8)}return QRCode.createBytes(i,r)};
  QRCode.createBytes=function(e,t){var n=0,r=0,i=0,o=new Array(t.length),a=new Array(t.length);for(var s=0;s<t.length;s++){var u=t[s].dataCount,f=t[s].totalCount-u;r=Math.max(r,u);i=Math.max(i,f);o[s]=new Array(u);for(var l=0;l<o[s].length;l++)o[s][l]=0xff&e.buffer[l+n];n+=u;var c=QRUtil.getErrorCorrectPolynomial(f);var d=new QRPolynomial(o[s],c.getLength()-1);var g=d.mod(c);a[s]=new Array(c.getLength()-1);for(var l=0;l<a[s].length;l++){var p=l+g.getLength()-a[s].length;a[s][l]=(p>=0)?g.get(p):0}}var h=0;for(var l=0;l<t.length;l++)h+=t[l].totalCount;var v=new Array(h),m=0;for(var l=0;l<r;l++)for(var s=0;s<t.length;s++)if(l<o[s].length)v[m++]=o[s][l];for(var l=0;l<i;l++)for(var s=0;s<t.length;s++)if(l<a[s].length)v[m++]=a[s][l];return v};
  var QRMode={MODE_8BIT_BYTE:4};
  var QRErrorCorrectLevel={L:1,M:0,Q:3,H:2};
  var QRMaskPattern={PATTERN000:0,PATTERN001:1,PATTERN010:2,PATTERN011:3,PATTERN100:4,PATTERN101:5,PATTERN110:6,PATTERN111:7};
  var QRUtil={G15:(1<<10)|(1<<8)|(1<<5)|(1<<4)|(1<<2)|(1<<1)|(1<<0),G18:(1<<12)|(1<<11)|(1<<10)|(1<<9)|(1<<8)|(1<<5)|(1<<2)|(1<<0),G15_MASK:(1<<14)|(1<<12)|(1<<10)|(1<<4)|(1<<1),getBCHTypeInfo:function(e){var t=e<<10;while(QRUtil.getBCHDigit(t)-QRUtil.getBCHDigit(QRUtil.G15)>=0)t^=QRUtil.G15<<(QRUtil.getBCHDigit(t)-QRUtil.getBCHDigit(QRUtil.G15));return((e<<10)|t)^QRUtil.G15_MASK},getBCHTypeNumber:function(e){var t=e<<12;while(QRUtil.getBCHDigit(t)-QRUtil.getBCHDigit(QRUtil.G18)>=0)t^=QRUtil.G18<<(QRUtil.getBCHDigit(t)-QRUtil.getBCHDigit(QRUtil.G18));return(e<<12)|t},getBCHDigit:function(e){var t=0;while(e!=0){t++;e>>>=1}return t},getPatternPosition:function(v){if(v===1)return [];var na=Math.floor(v/7)+2;var step=(v===32)?26:Math.ceil((v*4+4)/(na*2-2))*2;var res=[6];for(var p=v*4+10;res.length<na;p-=step)res.splice(1,0,p);return res},getMask:function(e,t,n){switch(e){case QRMaskPattern.PATTERN000:return(t+n)%2==0;case QRMaskPattern.PATTERN001:return t%2==0;case QRMaskPattern.PATTERN010:return n%3==0;case QRMaskPattern.PATTERN011:return(t+n)%3==0;case QRMaskPattern.PATTERN100:return(Math.floor(t/2)+Math.floor(n/3))%2==0;case QRMaskPattern.PATTERN101:return(t*n)%2+(t*n)%3==0;case QRMaskPattern.PATTERN110:return((t*n)%2+(t*n)%3)%2==0;case QRMaskPattern.PATTERN111:return((t*n)%3+(t+n)%2)%2==0}},getErrorCorrectPolynomial:function(e){var t=new QRPolynomial([1],0);for(var n=0;n<e;n++)t=t.multiply(new QRPolynomial([1,QRMath.gexp(n)],0));return t},getLengthInBits:function(e,t){if(1<=t&&t<10)return 8;else if(t<27)return 16;else return 16},getLostPoint:function(e){var t=e.getModuleCount(),n=0;for(var r=0;r<t;r++){for(var i=0;i<t;i++){var o=0,a=e.isDark(r,i);for(var s=-1;s<=1;s++){if(r+s<0||t<=r+s)continue;for(var u=-1;u<=1;u++){if(i+u<0||t<=i+u)continue;if(s==0&&u==0)continue;if(a==e.isDark(r+s,i+u))o++}}if(o>5)n+=(3+o-5)}}return n}};
  var QRMath={glog:function(e){return QRMath.LOG_TABLE[e]},gexp:function(e){while(e<0)e+=255;while(e>=256)e-=255;return QRMath.EXP_TABLE[e]},EXP_TABLE:new Array(256),LOG_TABLE:new Array(256)};
  for(var d=0;d<8;d++)QRMath.EXP_TABLE[d]=1<<d;for(var d=8;d<256;d++)QRMath.EXP_TABLE[d]=QRMath.EXP_TABLE[d-4]^QRMath.EXP_TABLE[d-5]^QRMath.EXP_TABLE[d-8]^QRMath.EXP_TABLE[d-6];for(var d=0;d<255;d++)QRMath.LOG_TABLE[QRMath.EXP_TABLE[d]]=d;
  function QRPolynomial(e,t){var n=0;while(n<e.length&&e[n]==0)n++;this.num=new Array(e.length-n+t);for(var r=0;r<e.length-n;r++)this.num[r]=e[r+n]}
  QRPolynomial.prototype={get:function(e){return this.num[e]},getLength:function(){return this.num.length},multiply:function(e){var t=new Array(this.getLength()+e.getLength()-1);for(var n=0;n<this.getLength();n++){for(var r=0;r<e.getLength();r++){t[n+r]^=QRMath.gexp(QRMath.glog(this.get(n))+QRMath.glog(e.get(r)))}}return new QRPolynomial(t,0)},mod:function(e){if(this.getLength()-e.getLength()<0)return this;var t=QRMath.glog(this.get(0))-QRMath.glog(e.get(0));var n=new Array(this.getLength());for(var r=0;r<this.getLength();r++)n[r]=this.get(r);for(var r=0;r<e.getLength();r++)n[r]^=QRMath.gexp(QRMath.glog(e.get(r))+t);return new QRPolynomial(n,0).mod(e)}};
  function RSBlock(e,t){this.totalCount=e;this.dataCount=t}
  RSBlock.ECC_PER_BLOCK_L=[-1,7,10,15,20,26,18,20,24,30,18,20,24,26,30,22,24,28,30,28,28,28,28,30,30,26,28,30,30,30,30,30,30,30,30,30,30,30,30,30,30];
  RSBlock.NUM_BLOCKS_L=[-1,1,1,1,1,1,2,2,2,2,4,4,4,4,4,6,6,6,6,7,8,8,9,9,10,12,12,12,13,14,15,16,17,18,19,19,20,21,22,24,25];
  RSBlock.getNumRawDataModules=function(v){var r=(16*v+128)*v+64;if(v>=2){var na=Math.floor(v/7)+2;r-=(25*na-10)*na-55;if(v>=7)r-=36}return r};
  RSBlock.getRSBlocks=function(v,ecl){if(ecl!==QRErrorCorrectLevel.L)throw new Error("Only L");if(v<1||v>40)return[];var raw=Math.floor(RSBlock.getNumRawDataModules(v)/8),nb=RSBlock.NUM_BLOCKS_L[v],ecc=RSBlock.ECC_PER_BLOCK_L[v];var nShort=nb-raw%nb,shortLen=Math.floor(raw/nb),out=[];for(var i=0;i<nb;i++){var tot=shortLen+(i>=nShort?1:0);out.push(new RSBlock(tot,tot-ecc))}return out};
  function QRBitBuffer(){this.buffer=[];this.length=0}
  QRBitBuffer.prototype={get:function(e){return((this.buffer[Math.floor(e/8)]>>>(7-(e%8)))&1)==1},put:function(e,t){for(var n=0;n<t;n++)this.putBit(((e>>>(t-n-1))&1)==1)},getLengthInBits:function(){return this.length},putBit:function(e){var t=Math.floor(this.length/8);if(this.buffer.length<=t)this.buffer.push(0);if(e)this.buffer[t]|=0x80>>>(this.length%8);this.length++}};
  function QR8bitByte(e){this.mode=QRMode.MODE_8BIT_BYTE;this.data=e}
  QR8bitByte.prototype={getLength:function(){return utf8Encode(this.data).length},write:function(e){var bytes=utf8Encode(this.data);for(var t=0;t<bytes.length;t++)e.put(bytes[t],8)}};
  function utf8Encode(str){var out=[];for(var i=0;i<str.length;i++){var c=str.charCodeAt(i);if(c<128)out.push(c);else if(c<2048){out.push(192|(c>>6));out.push(128|(c&63))}else if(c<55296||c>=57344){out.push(224|(c>>12));out.push(128|((c>>6)&63));out.push(128|(c&63))}else{i++;var c2=str.charCodeAt(i);var cp=((c&1023)<<10)|(c2&1023)|65536;out.push(240|(cp>>18));out.push(128|((cp>>12)&63));out.push(128|((cp>>6)&63));out.push(128|(cp&63))}}return out}
  function dataCapacityBits(v){var b=RSBlock.getRSBlocks(v,QRErrorCorrectLevel.L),n=0;for(var i=0;i<b.length;i++)n+=b[i].dataCount;return n*8}
  function buildQr(text){var bytes=utf8Encode(text).length;for(var v=1;v<=40;v++){if(4+QRUtil.getLengthInBits(QRMode.MODE_8BIT_BYTE,v)+bytes*8>dataCapacityBits(v))continue;var qr=new QRCode(v,QRErrorCorrectLevel.L);qr.addData(text);try{qr.make()}catch(err){continue}return{qr:qr,version:v,bytes:bytes}}throw new Error("Message too long for QR code")}
  function generate(text){var r=buildQr(text),qr=r.qr,count=qr.getModuleCount(),quiet=4,total=count+quiet*2;var scale=Math.max(4,Math.floor(840/total));var canvas=document.createElement('canvas');canvas.width=total*scale;canvas.height=total*scale;var ctx=canvas.getContext('2d');ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000000';for(var y=0;y<count;y++)for(var x=0;x<count;x++)if(qr.isDark(y,x))ctx.fillRect((x+quiet)*scale,(y+quiet)*scale,scale,scale);return{dataUrl:canvas.toDataURL('image/png'),version:r.version,bytes:r.bytes,modules:count}}
  return{generate:generate,generateDataUrl:function(text){return generate(text).dataUrl}};
})();
